services:
  - type: web
    name: dhishan-backend
    env: node
    region: singapore # or singapore if you're in India
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
